### ISSUE TITLE
new york times newsletters?

### ISSUE THREAD

**Issue by bmccann36** [j6k4m8/goosepaper#28]
I started building something really similar to this then stumbled upon this project. This looks nice and you are pretty far along so maybe its better if I just help on this. 
**Key differences**
- I am just trying to do the nyt newseltters https://www.nytimes.com/newsletters
- I am converting them to ePub format because I find that renders best on the remarkable 

@j6k4m8 It seems like you are grappling with the problem of offering an automated web based service that would deliver the paper to people's devices. I've been exploring this too but the main issue is it requires the developer to store a permanent token server side and a lot of potential users might not be comfortable with that? Am I right?
Let me know if you are interested in adding NYT newsletters. I have a working prototype still with some bugs. Also mine is in .js
Either way would like to chat!

**Comment by j6k4m8** [comment]
@bmccann36 hi!! would love to welcome you to the project if you are interested!

@sterlingbaldwin helpfully added an [epub Goosepaper exporter](https://github.com/j6k4m8/goosepaper/blob/master/goosepaper/goosepaper.py#L108-L170) so we can write to epub as well. (I've been using PDFs but I think you've convinced me to switch!)

If you are interested in contributing a NYT newsletter endpoint here, probably the easiest way is to add a new `StoryProvider` for NYT newsletters. The `LoremStoryProvider` ([link](https://github.com/j6k4m8/goosepaper/blob/master/goosepaper/storyprovider.py#L17-L32)) is a super simple `StoryProvider` that just returns _lorem ipsum_ text, and may serve as a good template to start. Would love to help you add this!!

With respect to a web service to design and deliver these: Unfortunately, you're exactly right. reMarkable doesn't offer any way to extend partial authorization to 3rd party apps, so for now a user would have to opt-in to sharing a device token. (That's why in addition to hosting the web apps, I'm planning on keeping everything open-source. Doesn't fix it, but makes it less mysterious.)

My hope, in pursuit of minimizing surface-area, is to reuse the same code and token management system as I've already got running for the public instance of [ReMailable](https://remailable.getneutrality.org/). And my secret plan to take over the world is to someday add third-party authorization to _that_, so that a third party can borrow a temporary upload-only token from ReMailable, rather than needing to get their own device token. Idk!! thinking out loud. Still doesn't solve the problem of sharing with _remailable_ in the first place, but hopefully lowers the barrier to entry in general.

**Comment by bmccann36** [comment]
@j6k4m8  cool I will check out the story provider template, sounds like I can plug in so long as I implement that interface

Yes the permanent token problem is a tricky one. I think it helps if you make it clear to the user that they can unpair the service at any time by going to remarkable and removing the paired device. However that still means that the token owner can read AND DELETE all files on that user's device. I think most users would never consider or be aware of that and it puts a lot of responsibility on you as the token owner. It would help if ReMarkable offered the capability to issue scoped tokens i.e. tokens that allow the application to read and write to only one folder perhaps? I doubt they'd ever do that though because they don't seem to have the bandwidth or interest to allow third party extensions. 

Perhaps you could offer an alternative desktop app version (maybe using electron) for those with security concerns?

**Comment by j6k4m8** [comment]
Awesome!! Let me know if I can be helpful to you. If you want, feel free to start a PR and I'll try to follow along during dev!

Have definitely considered desktop app versions, though at least for now that's way beyond the level of support I'd be able to commit to something like this. But happy to think more about that!

**Comment by sterlingbaldwin** [comment]
It would be really nice if the reMarkable folks could add scoped tokens, so it would be possible to give someone upload permission without full read/write/delete access. I emailed their support about plans for support for 3rd party developers and got a form letter back which didnt really say anything.

**Comment by sterlingbaldwin** [comment]
@bmccann36 I think getting the NYT newsletters would be pretty easy, just create a NewsLetterStoryProvider, have it use `requests` to grab whatevers at `https://static.nytimes.com/email-content/<THE_NEWSLETTER_YOU_WANT>_sample.html?action=click&module=nl-index-see-the-latest` and run it through the `readability` module [like its done here](https://github.com/j6k4m8/goosepaper/blob/master/goosepaper/rss.py#L28) and ask for it in the epub form. The hardest part will probably be getting the correct URLs for the newsletters.

**Comment by j6k4m8** [comment]
heh @sterlingbaldwin I'll bet you got the same email I got when I asked... :(

**Comment by j6k4m8** [comment]
Hey @bmccann36! Curious if you're still interested in collab'ing here. I'd be happy to do a quick zoom call to pair-program on some of this if you'd like! No pressure, just wanted to offer in case you're blocked.

**Comment by j6k4m8** [comment]
Just added these here: https://github.com/j6k4m8/auxiliary-goose/pull/4

Let me know if you try it out and run into any trouble! Happy to debug together.
