### ISSUE TITLE
Couldn't find config file 

### ISSUE THREAD

**Issue by WUYEAHS** [j6k4m8/goosepaper#76]
Hello, this is my first time using docker, I'm not familiar with this. I'm not sure about that how do I start with **step 0: write your config file**. I just download docker and run the step 1 code in terminal. And it started to download, after that shows the following:
Couldn't find config file (mount/example-config.json) specified on the command line. Aborting. 

Did I do something wrong? Thank you.

<img width="633" alt="Screenshot 2023-03-13 at 9 54 06 PM" src="https://user-images.githubusercontent.com/55338852/224725054-348c0c36-0fbb-4e1d-8aa4-b0028e00c497.png">
<img width="1076" alt="Screenshot 2023-03-13 at 9 54 14 PM" src="https://user-images.githubusercontent.com/55338852/224725101-09d7ab96-dc55-40b0-aaf7-75b70ff44ba8.png">

**Comment by j6k4m8** [comment]
Hi @WUYEAHS! Sorry for the delay in response; here's the short version of what's happening;

In order to use goosepaper, you give the tool a JSON config file that tells it the data sources you want it to pull from. Docker doesn't get to see anything on your machine unless you explicitly show it, so in the command, we do the following:


```bash
-v $(pwd):/goosepaper/mount
```

This says, "make the CURRENT directory where I run this command (in other words, the output of running `pwd`) visible to the container at `/goosepaper/mount`. Therefore, if you run this in the goosepaper directory, the goosepaper directory will be available in the container at `/goosepaper/mount/README.md`, etc.

Then Goosepaper takes a command-line flag that points it to the config file; we say 

```bash
-c /goosepaper/mount/example-config.json
```

to tell goosepaper that the config file it should use lives at that path; in other words, on our HOST computer at `$(pwd)/example-config.json`. So if you run this after cloning this repository, you'll wind up using the example config that I've listed which has some basic settings in it. A good place to start, since we know that config file works! 

You can also run this on your OWN config by changing `example-config.json` and running the docker command **from inside the goosepaper repo directory**, or you can run it from another directory that has a config file and just change the `-c` flag as well.

Does that make sense? Let me know if I can give you some more pointers to get started! :)

**Comment by j6k4m8** [comment]
@WUYEAHS gonna close this for now, let me know if you'd like some more pointers!
